// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudDatastreamV1
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Log definition for activities related to a stream.
public struct StreamActivityLogEntry: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A code representing the event.
  public var eventCode: Swift.String = Swift.String()

  /// A free-text message describing the event.
  public var eventMessage: Swift.String = Swift.String()

  public var eventPayload: OneOf_EventPayload? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `StreamActivityLogEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamActivityLogEntry().with { $0.eventCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let eventCode = CodingKeys(stringValue: "eventCode")
    static let eventMessage = CodingKeys(stringValue: "eventMessage")
    static let streamStateChange = CodingKeys(stringValue: "streamStateChange")

    static let _knownKeys: Set<Swift.String> = [
      "eventCode",
      "eventMessage",
      "streamStateChange",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eventCode) {
      self.eventCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eventMessage) {
      self.eventMessage = value
    }

    var eventPayload: OneOf_EventPayload? = nil
    let eventPayloadCheckAndSet = {
      if eventPayload != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'eventPayload'"))
      }
      eventPayload = $0
    }
    if let streamStateChange = try container.decodeIfPresent(
      StreamActivityLogEntry.StreamStateChange?.self, forKey: .streamStateChange)
    {
      try eventPayloadCheckAndSet(.streamStateChange(streamStateChange))
    }
    self.eventPayload = eventPayload
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.eventCode, forKey: .eventCode)
    try container.encode(self.eventMessage, forKey: .eventMessage)

    if let choice = self.eventPayload {
      switch choice {
      case .streamStateChange(let value):
        try container.encode(value, forKey: .streamStateChange)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Payload for a change in the state of a stream.
  public struct StreamStateChange: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. The new stream state.
    public var newState: GoogleCloudDatastreamV1.Stream.State = GoogleCloudDatastreamV1.Stream
      .State()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `StreamStateChange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StreamStateChange().with { $0.newState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let newState = CodingKeys(stringValue: "newState")

      static let _knownKeys: Set<Swift.String> = [
        "newState"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        GoogleCloudDatastreamV1.Stream.State.self, forKey: .newState)
      {
        self.newState = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.newState, forKey: .newState)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.datastream.logging.v1.StreamActivityLogEntry.StreamStateChange"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_EventPayload: Codable, Equatable, Sendable {
    /// A payload for a change in the state of a stream.
    indirect case streamStateChange(StreamActivityLogEntry.StreamStateChange?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.logging.v1.StreamActivityLogEntry"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
